/**
 * Phase 11: Bundle the ncc output into the Tauri sidecar location.
 *
 * Tauri sidecar binaries must be named with the Rust target triple, e.g.:
 *   server-aarch64-apple-darwin   (Apple Silicon Mac)
 *   server-x86_64-apple-darwin    (Intel Mac)
 *
 * Because better-sqlite3 is a native module it cannot be embedded in a single
 * self-contained binary using pkg or Node.js SEA. Instead we:
 *   1. Copy the ncc output dir (JS bundle + .node files) into src-tauri/binaries/server-bundle/
 *   2. Write a shell-script launcher at src-tauri/binaries/server-{triple}
 *      that resolves and runs index.js via the system node binary.
 *
 * Note: For distribution without assuming Node.js on the user's PATH you would
 * need to ship node itself as part of the app (e.g. using @electron/node-gyp-rebuild
 * or shipping a standalone Bun binary). That is out of scope for this phase.
 */

import { execSync } from "node:child_process";
import { cpSync, rmSync, writeFileSync, chmodSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const serverRoot = path.resolve(__dirname, "..");
const desktopRoot = path.resolve(serverRoot, "../desktop");
const binariesDir = path.resolve(desktopRoot, "src-tauri/binaries");

// Detect the Rust target triple for this machine
let triple;
try {
  triple = execSync("rustc -vV", { encoding: "utf8" })
    .split("\n")
    .find((l) => l.startsWith("host:"))
    ?.split(": ")[1]
    ?.trim();
} catch {
  triple = "aarch64-apple-darwin";
}

if (!triple) {
  console.error("Could not determine Rust target triple. Is Rust installed?");
  process.exit(1);
}

const nccOut = path.resolve(serverRoot, "dist/sidecar");
if (!existsSync(nccOut)) {
  console.error(`ncc output not found at ${nccOut} — run 'pnpm bundle' first`);
  process.exit(1);
}

// 1. Copy the esbuild bundle into binaries/server-bundle/ (clean first to avoid stale symlinks)
const bundleDir = path.join(binariesDir, "server-bundle");
if (existsSync(bundleDir)) rmSync(bundleDir, { recursive: true, force: true });
mkdirSync(bundleDir, { recursive: true });
cpSync(nccOut, bundleDir, { recursive: true, dereference: true });
console.log(`Copied bundle → ${bundleDir}`);

// Copy the native better-sqlite3 packages (esbuild externals — Node.js resolves them at runtime)
// We copy the entire package directory so Node.js can resolve the package + its native bindings.
const nativePkgs = [
  "better-sqlite3-multiple-ciphers",
  "better-sqlite3",
  "bindings",
  "file-uri-to-path",
];
const nodeModulesOut = path.join(bundleDir, "node_modules");
mkdirSync(nodeModulesOut, { recursive: true });

for (const pkg of nativePkgs) {
  // Find the package in the server's pnpm virtual store
  // Resolve the real disk path of the package (follows pnpm symlinks)
  const candidates = [
    path.resolve(serverRoot, "node_modules", pkg),
    path.resolve(serverRoot, "../../node_modules", pkg),
  ];
  // Also search in pnpm virtual store for packages not directly linked
  const pnpmStore = path.resolve(serverRoot, "../../node_modules/.pnpm");
  if (existsSync(pnpmStore)) {
    const storeEntries = (await import("node:fs")).readdirSync(pnpmStore)
      .filter(d => d.startsWith(pkg + "@"))
      .map(d => path.join(pnpmStore, d, "node_modules", pkg));
    candidates.push(...storeEntries);
  }
  // Walk up and find via symlink resolution
  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      const dest = path.join(nodeModulesOut, pkg);
      // dereference: true follows symlinks (pnpm uses symlinks into its store)
      cpSync(candidate, dest, { recursive: true, dereference: true });
      console.log(`Copied ${pkg} → ${dest}`);
      break;
    }
  }
}

// 2. Write the shell-script launcher as binaries/server-{triple}
const sidecarPath = path.join(binariesDir, `server-${triple}`);
// Detect the absolute path of the node binary used to run this script,
// so the launcher can use the same node even when PATH is stripped in a GUI app.
const nodeBin = process.execPath;

const launcherScript = `#!/usr/bin/env bash
# Finwise server sidecar launcher — generated by scripts/copy-sidecar.mjs
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# macOS GUI apps launch with a stripped PATH — add common Node.js locations.
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

# In a packaged .app the bundle lives in Contents/Resources/ (added via tauri resources).
# In dev/sidecar-only mode it sits next to this script.
RESOURCES_DIR="$SCRIPT_DIR/../Resources"
if [ -f "$RESOURCES_DIR/binaries/server-bundle/index.js" ]; then
  BUNDLE_JS="$RESOURCES_DIR/binaries/server-bundle/index.js"
elif [ -f "$SCRIPT_DIR/server-bundle/index.js" ]; then
  BUNDLE_JS="$SCRIPT_DIR/server-bundle/index.js"
else
  echo "[finwise-server] ERROR: server-bundle/index.js not found" >&2
  exit 1
fi

# Prefer the exact node binary that was used at build time; fall back to PATH.
NODE_BIN="${nodeBin}"
if [ ! -x "$NODE_BIN" ]; then
  NODE_BIN="node"
fi

exec "$NODE_BIN" "$BUNDLE_JS"
`;

writeFileSync(sidecarPath, launcherScript, { encoding: "utf8" });
chmodSync(sidecarPath, 0o755);
console.log(`Created launcher → ${sidecarPath}`);
console.log(`\nSidecar ready: server-${triple}`);
console.log("Run: cd ../desktop && pnpm tauri dev");
